In [1]:
%matplotlib qt
import numpy as np
import matplotlib.pyplot as plt

from calc_flatfield import *#calc_flatfield
import glob
from kll import kll

In [2]:
dark_file = '/home/ulyanov/data/solo/phi/dark/solo_CAL1_phi-fdt-dark_20240205T033810_V202402220119C_0422051001.fits.gz'
deadpix_file = '/home/ulyanov/data/solo/phi/dead_pixels/PHI_deadpix_maskcorrected.fits'
prefilter_file = '/home/ulyanov/data/solo/phi/prefilter/phi-fdt-prefilter_20250916T023002_V202607231634C_0569160250.txt'
distortion_file = '/home/ulyanov/data/solo/phi/distortion/fdt/distortion_cor.npz'

In [3]:
folders = sorted(glob.glob('/home/ulyanov/data/solo/phi/flat/fdt/calibration/*'))
folders

['/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-09-26',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-16',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-27',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-12-02',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-01-19',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-03-10',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-15',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-23',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-04-25']

In [4]:
folder = folders[-2]

In [5]:
calc_flatfield(folder, 'temp',
               dark_file=dark_file,
               deadpix_file=deadpix_file,
               prefilter_file=prefilter_file,
               distortion_file=distortion_file,
               quicklook=False)

looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10/solo_L1_phi-fdt-ilam_20260310T040003_V202606241235C_0663100100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10/solo_L1_phi-fdt-ilam_20260310T043205_V202606241634C_0663100300.fits.gz
reading and preprocessing the data
dark signal file is: /home/ulyanov/data/solo/phi/dark/solo_CAL1_phi-fdt-dark_20240205T033810_V202402220119C_0422051001.fits.gz
dead pixels file is: /home/ulyanov/data/solo/phi/dead_pixels/PHI_deadpix_maskcorrected.fits
prefilter file is: /home/ulyanov/data/solo/phi/prefilter/phi-fdt-prefilter_20250916T023002_V202607231634C_0569160250.txt
distortion file is: /home/ulyanov/data/solo/phi/distortion/fdt/distortion_cor.npz
distance is: 0.32765725 AU
PMP SP temperature is: 45 C
FG SP temperature is: 66 C
continuum position is: blue
wavelengths are: [617

/home/ulyanov/PycharmProjects/flatfield/src/kll.py:68: RuntimeWarning: divide by zero encountered in divide
  A += np.nan_to_num((y - A) * w / W)
/home/ulyanov/PycharmProjects/flatfield/src/kll.py:69: RuntimeWarning: divide by zero encountered in divide
  B += np.nan_to_num((x - B) * w / W)


calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 995.2234101235651 996.727647097659
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:357: RuntimeWarning: divide by zero encountered in divide
  G = (a * v - b * u) / (a * d - b ** 2)
/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:367: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20260310T040003_V202608071840C_0663100100.fits
ghost map saved to file: temp/phi-fdt-ghost_20260310T040003_V202608071840C_0663100100.fits
cavity map saved to file: temp/phi-fdt-cavity_20260310T040003_V202608071840C_0663100100.fits
done
