In [1]:
from calc_flatfield import calc_flatfield
import glob

In [2]:
dark_file = '/home/ulyanov/data/solo/phi/dark/solo_CAL1_phi-fdt-dark_20240205T033810_V202402220119C_0422051001.fits.gz'
deadpix_file = '/home/ulyanov/data/solo/phi/dead_pixels/phi-fdt-deadpix_20250915T140003_V202609041457C_0569150100.fits'
prefilter_file = '/home/ulyanov/data/solo/phi/prefilter/phi-fdt-prefilter_20250916T023002_V202607231634C_0569160250.txt'
distortion_file = '/home/ulyanov/data/solo/phi/distortion/fdt/distortion_cor.npz'

In [3]:
folders = sorted(glob.glob('/home/ulyanov/data/solo/phi/flat/fdt/calibration/*'))[::-1]
folders

['/home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-04-25',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-23',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-15',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-03-10',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-01-19',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-12-02',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-27',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-16',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-09-26',
 '/home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30']

In [4]:
for folder in folders:

    calc_flatfield(folder, 'temp',
                   dark_file=dark_file,
                   deadpix_file=deadpix_file,
                   prefilter_file=prefilter_file,
                   distortion_file=distortion_file,
                   niter=100,
                   quicklook=True)

looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-04-25
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-04-25/solo_L1_phi-fdt-ilam_20260425T230003_V202605051433C_0664250100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-04-25/solo_L1_phi-fdt-ilam_20260425T233204_V202605201634C_0664250300.fits.gz
reading and preprocessing the data
dark signal file is: /home/ulyanov/data/solo/phi/dark/solo_CAL1_phi-fdt-dark_20240205T033810_V202402220119C_0422051001.fits.gz
dead pixels file is: /home/ulyanov/data/solo/phi/dead_pixels/PHI_deadpix_maskcorrected.fits
prefilter file is: /home/ulyanov/data/solo/phi/prefilter/phi-fdt-prefilter_20250916T023002_V202607231634C_0569160250.txt
distortion file is: /home/ulyanov/data/solo/phi/distortion/fdt/distortion_cor.npz
distance is: 0.80967238 AU
PMP SP temperature is: 45 C
FG SP temperature is: 61 C
continuum position is: blue
wavelengths are: [617

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[ 999.7177 1039.7714]
 [ 934.3059  988.3422]
 [ 970.6268 1016.9565]
 [1019.2718 1054.9824]
 [1111.214  1126.8979]
 [ 948.7445 1104.9382]
 [ 977.4781 1068.5874]
 [1015.6394 1019.7628]
 [1087.1068  928.4059]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 971.4938628394204 976.846358032454
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.008829125753559
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20260425T230003_V202608261804C_0664250100.fits
ghost map saved to file: temp/phi-fdt-ghost_20260425T230003_V202608261804C_0664250100.fits
cavity map saved to file: temp/phi-fdt-cavity_20260425T230003_V202608261804C_0664250100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20260425T230003_V202608261804C_0664250100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10/solo_L1_phi-fdt-ilam_20260310T040003_V202606241235C_0663100100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2026-03-10/solo_L1_phi-fdt-ilam_20260310T043205_

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[ 996.4147 1048.7939]
 [ 834.6403  921.7749]
 [ 924.4161  992.0585]
 [1044.9526 1086.6406]
 [1271.6866 1264.3187]
 [ 869.5087 1209.9097]
 [ 940.2686 1120.3276]
 [1035.1371  999.7214]
 [1212.8016  772.9205]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 995.4604472719877 996.4380868287692
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b
/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:333: RuntimeWarning: invalid value encountered in multiply
  W = I / np.abs(Q - F * I - G * I_).clip(sigma)


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.0272871577532263
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20260310T040003_V202608261828C_0663100100.fits
ghost map saved to file: temp/phi-fdt-ghost_20260310T040003_V202608261828C_0663100100.fits
cavity map saved to file: temp/phi-fdt-cavity_20260310T040003_V202608261828C_0663100100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20260310T040003_V202608261828C_0663100100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-23
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-23/solo_L1_phi-fdt-ilam_20250923T000503_V202512011636C_0569230100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-23/solo_L1_phi-fdt-ilam_20250923T005305

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[1005.4378 1043.5406]
 [ 845.1491  917.9965]
 [ 934.5464  988.2163]
 [1054.3504 1082.1297]
 [1277.9739 1257.5559]
 [ 880.0976 1203.7803]
 [ 949.8945 1114.9075]
 [1043.6963  995.6041]
 [1219.3874  771.8324]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 996.1240124101319 995.1194072624073
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b
/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:333: RuntimeWarning: invalid value encountered in multiply
  W = I / np.abs(Q - F * I - G * I_).clip(sigma)


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.030559407310037
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20250923T000503_V202608261853C_0569230100.fits
ghost map saved to file: temp/phi-fdt-ghost_20250923T000503_V202608261853C_0569230100.fits
cavity map saved to file: temp/phi-fdt-cavity_20250923T000503_V202608261853C_0569230100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20250923T000503_V202608261853C_0569230100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-15
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-15/solo_L1_phi-fdt-ilam_20250915T140003_V202511211337C_0569150100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-09-15/solo_L1_phi-fdt-ilam_20250915T144807_

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[1002.7253 1049.1408]
 [ 822.8072  907.8101]
 [ 923.2458  986.3999]
 [1057.6568 1091.7599]
 [1309.6955 1289.8476]
 [ 861.7204 1228.6703]
 [ 940.5535 1128.5945]
 [1046.2542  994.1659]
 [1244.125   742.1511]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 1000.842820948825 998.6953668390713
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance


/home/ulyanov/PycharmProjects/flatfield/src/kll.py:64: RuntimeWarning: divide by zero encountered in divide
  return np.nan_to_num(A / B)


normalizing transmittance
transmittance norm is: 1.0335580696938598
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20250915T140003_V202608261916C_0569150100.fits
ghost map saved to file: temp/phi-fdt-ghost_20250915T140003_V202608261916C_0569150100.fits
cavity map saved to file: temp/phi-fdt-cavity_20250915T140003_V202608261916C_0569150100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20250915T140003_V202608261916C_0569150100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-03-10
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-03-10/solo_L1_phi-fdt-ilam_20250310T080009_V202503131733C_0563100100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-03-10/solo_L1_phi-fdt-ilam_20250310T084808_V202503141833C_0563100300.fits.gz
reading and preprocessing the data
dark 

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/miniconda3/lib/python3.11/site-packages/numpy/_core/_methods.py:132: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)


disk centers are: [[ 993.4964 1033.2528]
 [ 889.9943  951.8583]
 [ 947.7934  997.0561]
 [1024.9963 1057.6507]
 [1170.7086 1171.5963]
 [ 912.673  1136.9133]
 [ 958.0642 1079.2479]
 [1019.2162 1002.0619]
 [1133.2142  856.5028]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 979.7301369432375 978.7475670550978
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.0197332168171274
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20250310T080009_V202608261939C_0563100100.fits
ghost map saved to file: temp/phi-fdt-ghost_20250310T080009_V202608261939C_0563100100.fits
cavity map saved to file: temp/phi-fdt-cavity_20250310T080009_V202608261939C_0563100100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20250310T080009_V202608261939C_0563100100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-01-19
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-01-19/solo_L1_phi-fdt-ilam_20250119T210009_V202501210811C_0561190100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2025-01-19/solo_L1_phi-fdt-ilam_20250119T213207

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/miniconda3/lib/python3.11/site-packages/numpy/_core/_methods.py:132: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)


disk centers are: [[ 998.7065 1035.2689]
 [ 941.1653  990.1125]
 [ 973.2463 1015.1455]
 [1016.4833 1048.7732]
 [1097.4307 1112.166 ]
 [ 953.9589 1092.8269]
 [ 978.6959 1060.6559]
 [1012.3439 1017.6458]
 [1075.9698  936.3424]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 970.0185722408314 974.7463541754105
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.004800183559409
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20250119T210009_V202608262003C_0561190100.fits
ghost map saved to file: temp/phi-fdt-ghost_20250119T210009_V202608262003C_0561190100.fits
cavity map saved to file: temp/phi-fdt-cavity_20250119T210009_V202608262003C_0561190100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20250119T210009_V202608262003C_0561190100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-12-02
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-12-02/solo_L1_phi-fdt-ilam_20241202T123003_V202604252350C_0472020100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-12-02/solo_L1_phi-fdt-ilam_20241202T130205_

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[ 998.2005 1035.8966]
 [ 938.6623  989.2185]
 [ 971.6466 1015.1245]
 [1015.902  1049.8295]
 [1098.815  1114.9819]
 [ 950.643  1094.6966]
 [ 977.0923 1061.4617]
 [1012.0621 1017.3701]
 [1077.4559  934.3894]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 969.8661374296096 974.6685196520789
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.0055240440748667
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20241202T123003_V202608262027C_0472020100.fits
ghost map saved to file: temp/phi-fdt-ghost_20241202T123003_V202608262027C_0472020100.fits
cavity map saved to file: temp/phi-fdt-cavity_20241202T123003_V202608262027C_0472020100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20241202T123003_V202608262027C_0472020100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-27
found 8 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-27/solo_L1_phi-fdt-ilam_20241027T233003_V202604252350C_0470270100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-27/solo_L1_phi-fdt-ilam_20241027T235804

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[ 996.4641 1032.9258]
 [ 906.8196  962.5372]
 [ 956.9158 1001.6908]
 [1023.384  1054.0162]
 [1148.0304 1152.0359]
 [ 925.8492 1121.8742]
 [ 965.2114 1072.2873]
 [1017.8504 1005.887 ]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 976.2780074636737 977.6702605774258
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b
/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:333: RuntimeWarning: invalid value encountered in multiply
  W = I / np.abs(Q - F * I - G * I_).clip(sigma)


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.0151327466503353
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20241027T233003_V202608262048C_0470270100.fits
ghost map saved to file: temp/phi-fdt-ghost_20241027T233003_V202608262048C_0470270100.fits
cavity map saved to file: temp/phi-fdt-cavity_20241027T233003_V202608262048C_0470270100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20241027T233003_V202608262048C_0470270100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-16
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-16/solo_L1_phi-fdt-ilam_20241016T113003_V202604260024C_0470160100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-10-16/solo_L1_phi-fdt-ilam_20241016T120203

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[ 992.2863 1036.3789]
 [ 872.5305  942.3339]
 [ 939.4208  994.7555]
 [1028.8954 1064.8925]
 [1196.4962 1196.4147]
 [ 898.5102 1156.1428]
 [ 951.1225 1089.332 ]
 [1021.0241  999.9296]
 [1152.4259  832.168 ]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 984.0988189404598 986.4281226940307
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.0206490912212476
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20241016T113003_V202608262111C_0470160100.fits
ghost map saved to file: temp/phi-fdt-ghost_20241016T113003_V202608262111C_0470160100.fits
cavity map saved to file: temp/phi-fdt-cavity_20241016T113003_V202608262111C_0470160100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20241016T113003_V202608262111C_0470160100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-09-26
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-09-26/solo_L1_phi-fdt-ilam_20240926T114503_V202604251703C_0469260100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-09-26/solo_L1_phi-fdt-ilam_20240926T123308

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]


disk centers are: [[1006.5086 1044.2064]
 [ 834.2966  909.4465]
 [ 929.6816  984.3334]
 [1057.9025 1084.9418]
 [1298.3031 1273.4203]
 [ 871.3397 1215.071 ]
 [ 946.4442 1119.6908]
 [1046.8142  991.1893]
 [1235.027   750.8976]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 999.190036576044 999.5924626905478
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b


removing fringes
removing ghosts from data and recalculating transmittance


/home/ulyanov/PycharmProjects/flatfield/src/kll.py:64: RuntimeWarning: divide by zero encountered in divide
  return np.nan_to_num(A / B)


normalizing transmittance
transmittance norm is: 1.031168584929453
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20240926T114503_V202608262134C_0469260100.fits
ghost map saved to file: temp/phi-fdt-ghost_20240926T114503_V202608262134C_0469260100.fits
cavity map saved to file: temp/phi-fdt-cavity_20240926T114503_V202608262134C_0469260100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20240926T114503_V202608262134C_0469260100.png
done
looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30/solo_L1_phi-fdt-ilam_20240330T050009_V202604251526C_0463300100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30/solo_L1_phi-fdt-ilam_20240330T054806_V202604251535C_0463300300.fits.gz
reading and preprocessing the data
dark s

/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: divide by zero encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/PycharmProjects/flatfield/src/classical_estimates.py:42: RuntimeWarning: invalid value encountered in divide
  data_ /= data_[contpos]
/home/ulyanov/miniconda3/lib/python3.11/site-packages/numpy/_core/_methods.py:132: RuntimeWarning: invalid value encountered in reduce
  ret = umr_sum(arr, axis, dtype, out, keepdims, where=where)


disk centers are: [[ 994.6271 1036.7501]
 [ 825.9017  904.0131]
 [ 919.8194  977.7279]
 [1046.0981 1076.8833]
 [1283.275  1262.8449]
 [ 862.1389 1206.0256]
 [ 935.6909 1112.0448]
 [1034.8942  985.619 ]
 [1221.3181  748.3277]]
calculating mask
calculating cavity
calculating transmittance
correcting data for transmittance
realigning and demodulating the data
modulation matrix is:
[[ 1.0023  -0.64814 -0.56202 -0.51859]
 [ 1.0041   0.54693 -0.55299  0.633  ]
 [ 0.99523  0.46132  0.54165 -0.69603]
 [ 0.99838 -0.61944  0.66189  0.42519]]
calculating ghost reflection center
reflection center is: 998.682221641721 995.1984420747963
calculating instrumental polarization


/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:332: RuntimeWarning: divide by zero encountered in divide
  F = a / b
/home/ulyanov/PycharmProjects/flatfield/src/calc_flatfield.py:333: RuntimeWarning: invalid value encountered in multiply
  W = I / np.abs(Q - F * I - G * I_).clip(sigma)


removing fringes
removing ghosts from data and recalculating transmittance
normalizing transmittance
transmittance norm is: 1.0322929241082086
modulating flatfield
filling missing values
distorting flatfield
saving result
flatfield map saved to file: temp/phi-fdt-flat_20240330T050009_V202608262158C_0463300100.fits
ghost map saved to file: temp/phi-fdt-ghost_20240330T050009_V202608262158C_0463300100.fits
cavity map saved to file: temp/phi-fdt-cavity_20240330T050009_V202608262158C_0463300100.fits
making quicklook image
quicklook image saved to file: temp/phi-fdt-ilam_20240330T050009_V202608262158C_0463300100.png
done


In [4]:
folder = folders[-1]

In [5]:
calc_flatfield(folder, 'temp',
               dark_file=dark_file,
               deadpix_file=deadpix_file,
               prefilter_file=prefilter_file,
               distortion_file=distortion_file,
               niter=100,
               quicklook=False)

looking for files in folder: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30
found 9 input files
first input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30/solo_L1_phi-fdt-ilam_20240330T050009_V202604251526C_0463300100.fits.gz
last input file is: /home/ulyanov/data/solo/phi/flat/fdt/calibration/2024-03-30/solo_L1_phi-fdt-ilam_20240330T054806_V202604251535C_0463300300.fits.gz
reading and preprocessing the data
dark signal file is: /home/ulyanov/data/solo/phi/dark/solo_CAL1_phi-fdt-dark_20240205T033810_V202402220119C_0422051001.fits.gz
dead pixels file is: /home/ulyanov/data/solo/phi/dead_pixels/PHI_deadpix_maskcorrected.fits
prefilter file is: /home/ulyanov/data/solo/phi/prefilter/phi-fdt-prefilter_20250916T023002_V202607231634C_0569160250.txt
distortion file is: /home/ulyanov/data/solo/phi/distortion/fdt/distortion_cor.npz


KeyboardInterrupt: 